// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// Copies content to clipboard, hides the window, and simulates Ctrl+V.
	pasteItem: (contentType: string, textContent: string | null, imageData: string | null) => typedError<null, string>(__TAURI_INVOKE("paste_item", { contentType, textContent, imageData })),
	/**
	 *  Writes a file:// URI to the clipboard as text/uri-list, hides the window,
	 *  and simulates Ctrl+V. Wayland-only for now (shells out to wl-copy).
	 */
	pasteFileUri: (path: string) => typedError<null, string>(__TAURI_INVOKE("paste_file_uri", { path })),
	readClipboard: () => typedError<string, string>(__TAURI_INVOKE("read_clipboard")),
	readClipboardImage: () => typedError<[string, number, number] | null, string>(__TAURI_INVOKE("read_clipboard_image")),
	writeClipboard: (text: string) => typedError<null, string>(__TAURI_INVOKE("write_clipboard", { text })),
	writeClipboardImage: (base64Data: string) => typedError<null, string>(__TAURI_INVOKE("write_clipboard_image", { base64Data })),
	reinitializeClipboard: () => typedError<null, string>(__TAURI_INVOKE("reinitialize_clipboard")),
	parseEnvContent: (text: string) => __TAURI_INVOKE<([string, string])[]>("parse_env_content", { text }),
	setMonitoring: (enabled: boolean) => __TAURI_INVOKE<void>("set_monitoring", { enabled }),
	isWaylandSession: () => __TAURI_INVOKE<boolean>("is_wayland_session"),
	isCosmicDataControlEnabled: () => __TAURI_INVOKE<boolean>("is_cosmic_data_control_enabled"),
	dbGetAllItems: (limit: number, offset: number, favoritesFirst: boolean) => typedError<ClipboardItemRow[], string>(__TAURI_INVOKE("db_get_all_items", { limit, offset, favoritesFirst })),
	dbInsertItem: (params: InsertClipboardItemParams) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("db_insert_item", { params })),
	dbBumpItem: (id: number, sortOrder: string) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("db_bump_item", { id, sortOrder })),
	dbDeleteItem: (id: number) => typedError<null, string>(__TAURI_INVOKE("db_delete_item", { id })),
	dbClearAll: () => typedError<null, string>(__TAURI_INVOKE("db_clear_all")),
	dbToggleFavorite: (id: number) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("db_toggle_favorite", { id })),
	dbUpdateSortOrders: (items: UpdateSortOrderParams[]) => typedError<null, string>(__TAURI_INVOKE("db_update_sort_orders", { items })),
	dbDedupItem: (id: number) => typedError<number, string>(__TAURI_INVOKE("db_dedup_item", { id })),
	dbUpdateNote: (id: number, note: string | null) => typedError<ClipboardItemRow, string>(__TAURI_INVOKE("db_update_note", { id, note })),
	fetchLinkPreview: (url: string) => typedError<LinkPreviewData, string>(__TAURI_INVOKE("fetch_link_preview", { url })),
	/**
	 *  Downloads a media URL to a temporary file and returns the file path
	 *  along with a small PNG icon for the drag preview.
	 */
	downloadMediaToTemp: (url: string) => typedError<[string, string], string>(__TAURI_INVOKE("download_media_to_temp", { url })),
	getSetting: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_setting", { key })),
	setSetting: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_setting", { key, value })),
	getHostname: () => __TAURI_INVOKE<string>("get_hostname"),
	getNetworkInterfaces: () => __TAURI_INVOKE<NetworkInterfaceInfo[]>("get_network_interfaces"),
	syncStartServer: (port: number) => typedError<SyncStartResult, string>(__TAURI_INVOKE("sync_start_server", { port })),
	syncConnect: (address: string, pairingCode: string) => typedError<null, string>(__TAURI_INVOKE("sync_connect", { address, pairingCode })),
	syncCloudJoin: (relayUrl: string, authToken: string) => typedError<string, string>(__TAURI_INVOKE("sync_cloud_join", { relayUrl, authToken })),
	syncStop: () => typedError<null, string>(__TAURI_INVOKE("sync_stop")),
	mdnsStartDiscovery: () => typedError<null, string>(__TAURI_INVOKE("mdns_start_discovery")),
	mdnsStopDiscovery: () => typedError<null, string>(__TAURI_INVOKE("mdns_stop_discovery")),
};

/* Types */
export type ClipboardItemRow = {
	id: number,
	content_type: string,
	text_content: string | null,
	image_data: string | null,
	image_width: number | null,
	image_height: number | null,
	char_count: number | null,
	line_count: number | null,
	source_app: string | null,
	is_favorite: boolean,
	sort_order: string,
	copy_count: number,
	kv_key: string | null,
	detected_date: string | null,
	detected_color: string | null,
	is_env: boolean,
	is_secret: boolean,
	note: string | null,
	content_hash: string | null,
	created_at: string,
	updated_at: string,
};

export type InsertClipboardItemParams = {
	content_type: string,
	text_content: string | null,
	image_data: string | null,
	image_width: number | null,
	image_height: number | null,
	char_count: number | null,
	line_count: number | null,
	source_app: string | null,
	sort_order: string,
	kv_key: string | null,
	created_at: string,
	updated_at: string,
};

export type LinkPreviewData = {
	title: string | null,
	description: string | null,
	image: string | null,
	favicon: string | null,
	site_name: string | null,
};

export type NetworkInterfaceInfo = {
	name: string,
	ip: string,
};

export type SyncStartResult = {
	address: string,
	pairingCode: string,
};

export type UpdateSortOrderParams = {
	id: number,
	sort_order: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

